#INCLUDE <P18F452.INC>

#DEFINE BOTAO_RB3 PORTB,3     
#DEFINE BOTAO_RB4 PORTB,4
#DEFINE BOTAO_RB5 PORTB,5
#DEFINE LED_D0 PORTD,0         
#DEFINE LED_D1 PORTD,1
#DEFINE LED_D2 PORTD,2

 ; 4. VETOR DE RESET
ORG 0x00 
GOTO INICIO

; 5. INÍCIO DO PROGRAMA 
; CONFIGURAÇÕES INICIAIS (REGISTRADORES DE FUNÇÕES ;ESPECIAIS)
INICIO
    CLRF PORTD         ; LIMPA PORTD (ESCREVE ZERO EM TODOS OS PINOS DO PORTD)
    MOVLW B'00111000'     ; MOVE O VALOR BINÁRIO PARA O REGISTRADOR WORK 
    MOVWF TRISB     ; DEFINE RB3 COMO ENTRADA E DEMAIS COMO SAÍDA
    MOVLW B'00000000'     ; MOVE O VALOR BINÁRIO PARA O REGISTRADOR WORK
    MOVWF TRISD     ; DEFINE TODOS OS TERMINAIS DO PORTD COMO SAÍDA

; 6. FUNÇÃO PRINCIPAL
MAIN
    BTFSC BOTAO_RB5
    GOTO BOTAO_RB5_LIB
    BCF LED_D0
    BCF LED_D1
    BCF LED_D2
    GOTO MAIN
BOTAO_RB5_LIB 
    BTFSC BOTAO_RB3      ; O BOTÃO ESTÁ PRESSIONADO?
    GOTO BOTAO_RB3_LIB   ; NÃO, ENTÃO VÁ PARA A SUBROTINA DE BOTÃO LIBERADO    
    BSF LED_D0       ; ACENDE O LED
    BCF LED_D1
    GOTO PROXIMO        
BOTAO_RB3_LIB
    BCF LED_D0       ; APAGA O LED
    BSF LED_D1
PROXIMO
    BTFSC BOTAO_RB4      ; O BOTÃO ESTÁ PRESSIONADO?
    GOTO BOTAO_RB4_LIB   ; NÃO, ENTÃO VÁ PARA A SUBROTINA DE BOTÃO LIBERADO    
    BCF LED_D2       
    GOTO MAIN        
BOTAO_RB4_LIB
    BSF LED_D2       
    GOTO MAIN        
END              ; FIM DO PROGRAMA
