#INCLUDE <P18F452.INC>

	ORG 0X000;
	GOTO INICIO
	
INICIO	CLRF	PORTD ;LIMPA PORTD
    	CLRF	PORTB ;LIMPA PORTB
	
; DEFINE ENTRADAS E SAIDAS
	
	CLRF	TRISD;
	MOVLW	B'00011000'
	MOVWF	TRISB;
	
	CLRF PORTD;
	

BOTAO_1	BTFSC	PORTB, RB3
	GOTO	BOTAO_2
	BTG	PORTD, RD0 ; INVERTEMOS O SINAL ANTERIOR (TOGGLE) O ESTADO DO BIT 0
	GOTO	BOTAO_1

BOTAO_2	BTFSC	PORTB, RB4
	GOTO	BOTAO_1
	BTG	PORTD, RD1 ; INVERTE RD1 (INVERSOR DE SINAL) -> 0 = 1 E 1 = 0
	BTG	PORTD, RD2 ; INVERTE RD2 (INVERSOR DE SINAL) -> 0 = 1 E 1 = 0
	GOTO	BOTAO_1
	
	
	END

